import { SwapiResourceType, SwapiResourceMap } from './swapi-resource-map';

export const resourceDisplayOrder: {
  [K in SwapiResourceType]: (keyof SwapiResourceMap[K])[];
} = {
  people: [
    'id',
    'name',
    'birth_year',
    'eye_color',
    'gender',
    'hair_color',
    'height',
    'mass',
    'skin_color',
    'homeworld',
    'created',
    'edited',
    'url',
    'films',
    'species',
    'vehicles',
    'starships',
  ],
  planets: [
    'id',
    'name',
    'diameter',
    'rotation_period',
    'orbital_period',
    'gravity',
    'population',
    'climate',
    'terrain',
    'surface_water',
    'created',
    'edited',
    'url',
    'residents',
    'films',
  ],
  films: [
    'id',
    'title',
    'episode_id',
    'opening_crawl',
    'director',
    'producer',
    'release_date',
    'created',
    'edited',
    'url',
    'characters',
    'planets',
    'starships',
    'vehicles',
    'species',
  ],
  species: [
    'id',
    'name',
    'classification',
    'designation',
    'average_height',
    'average_lifespan',
    'eye_colors',
    'hair_colors',
    'skin_colors',
    'language',
    'homeworld',
    'created',
    'edited',
    'url',
    'people',
    'films',
  ],
  starships: [
    'id',
    'name',
    'model',
    'manufacturer',
    'starship_class',
    'MGLT',
    'cargo_capacity',
    'consumables',
    'cost_in_credits',
    'crew',
    'hyperdrive_rating',
    'length',
    'max_atmosphering_speed',
    'passengers',
    'created',
    'edited',
    'url',
    'pilots',
    'films',
  ],
  vehicles: [
    'id',
    'name',
    'model',
    'manufacturer',
    'vehicle_class',
    'length',
    'cost_in_credits',
    'crew',
    'passengers',
    'max_atmosphering_speed',
    'cargo_capacity',
    'consumables',
    'created',
    'edited',
    'url',
    'pilots',
    'films',
  ],
};
